# Generated by Django 5.0.1 on 2024-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroNacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_animal', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('peso', models.FloatField()),
                ('raza', models.CharField(max_length=100)),
                ('capa', models.CharField(max_length=100)),
            ],
        ),
    ]
